version: 2.1
orbs:
  architect: giantswarm/architect@4.24.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-build:
          name: go-build
          binary: security-pack-helper
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-security-pack-helper-to-quay
          image: "quay.io/giantswarm/security-pack-helper"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/


      - architect/push-to-docker:
          context: "architect"
          name: push-security-pack-helper-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/security-pack-helper"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-security-pack-helper-to-playground-catalog
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "security-pack-helper"
          persist_chart_archive: true
          requires:
            - push-security-pack-helper-to-quay
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
              
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-security-pack-helper-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "security-pack-helper"
          requires:
            - push-security-pack-helper-to-quay
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      # Run app-test-suite tests.
      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - push-security-pack-helper-to-playground-catalog
