apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    giantswarm.io/monitoring: "true"
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    targetPort: {{ .Values.metrics.containerPort }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
