checks:
  addAllBuiltIn: true
  exclude:
  - "host-network"  # Needed to connect to local etcd.
  - "minimum-three-replicas"
  - "no-liveness-probe"
  - "no-readiness-probe"
  - "required-annotation-email"
  - "required-label-owner"
  - "use-namespace"  # Handled in _resource.tpl
  - "exposed-services"  # Needed to scrape metrics when using host network.
