name: security-pack-helper
serviceType: managed

image:
  registry: docker.io
  name: giantswarm/security-pack-helper
  tag: v0.0.1
  pullPolicy: IfNotPresent

# The time in seconds after which periodic checks will be run again.
interval: 60
